export const ADD_NEW_ALGORITHM_START = 'ADD_NEW_ALGORITHM_START';
export const ADD_NEW_ALGORITHM_COMPLETE = 'ADD_NEW_ALGORITHM_COMPLETE';
export const FETCH_CURRENT_STATE_START = 'FETCH_CURRENT_STATE_START';
export const FETCH_CURRENT_STATE_COMPLETE = 'FETCH_CURRENT_STATE_COMPLETE';